stages:
  - build

before_script:
  - CI_REGISTRY_IMAGE = olezko46/runpod-sd-deliberate:latest

build:
  stage: build
  allow_failure: false
  image: docker:latest
  services:
    - docker:dind
  tags:
    - docker
  script:
    - docker build -t $CI_REGISTRY_IMAGE .
    - docker push $CI_REGISTRY_IMAGE


