#!/usr/bin/env python

import os
import shutil
from diffusers import StableDiffusionPipeline

MODEL_ID = "XpucT/Deliberate"
MODEL_CACHE = "diffusers-cache"


if os.path.exists(MODEL_CACHE):
    shutil.rmtree(MODEL_CACHE)
os.makedirs(MODEL_CACHE, exist_ok=True)


pipe = StableDiffusionPipeline.from_pretrained(
    MODEL_ID,
    cache_dir=MODEL_CACHE,
)